config/routes.rb
Rails.application.routes.draw do
  resources :libros
  get 'home/index'
  get 'phantom/index'
  get 'phantom/generic'
  get 'phantom/elements'
  get 'zelda/mostrar'

  #se pueden modificar las rutas 
  get 'index', to: "phantom#index"
  get "generic", to: "phantom#generic"
  get "elements", to: "phantom#elements"
  get "libros", to: "libros#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "phantom#index" # se descomenta y entonces cundo se ingresa a localhost la primera pag que aparece sera welcome/index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: %i[ show edit update destroy ]

  # GET /libros or /libros.json
  def index
    @libros = Libro.all #variable de instancia que se puede usar dentro del metodo, libro es el objeto
    ##.all select * from libros#active recolr ORM de rails hace el paralelismo entre el archivo y la tabla
  end

  # GET /libros/1 or /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros or /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully created." }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1 or /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully updated." }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1 or /libros/1.json
  def destroy
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url, notice: "Libro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:nombre, :descripcion, :paginas, :precio)
    end
end

app/controllers/phantom_controller.rb
class PhantomController < ApplicationController
  def index
  end

  def generic
  end

  def elements
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/zelda_controller.rb
class ZeldaController < ApplicationController
    def mostrar
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/phantom_helper.rb
module PhantomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!--CSS -->
    <%= stylesheet_link_tag 'fontawesome-all.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'noscript', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>


  </head>

  <body class="is-preload">
    <div id="wrapper">
      <%= render 'shared/header' %>
      <%= render 'shared/menu' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag "breakpoints.min" %>
    <%= javascript_include_tag "browser.min" %>
    <%= javascript_include_tag "jquery.min" %>
    <%= javascript_include_tag "main" %>
    <%= javascript_include_tag "util" %>

  </body>
</html>

app/views/libros/_form.html.erb
<%= form_with(model: libro) do |form| %>
  <% if libro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
        <% libro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :paginas, style: "display: block" %>
    <%= form.text_field :paginas %>
  </div>
  
  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div> 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/_libro.html.erb
<div id="<%= dom_id libro %>">
  <p>
    <strong>Nombre:</strong>
    <%= libro.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= libro.descripcion %>
  </p>

  <p>
    <strong>Paginas:</strong>
    <%= libro.paginas %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= libro.precio %>
  </p>

</div>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Show this libro", @libro %> |
  <%= link_to "Back to libros", libros_path %>
</div>

app/views/libros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libros</h1>

<%= link_to "Crear nuevo libro", new_libro_path %>
<hr>

<div id="libros"> 

    <!-- Table -->
    <section>        
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Páginas</th>
                        <th>Precio</th>
                        <th>Editar</th>
                        <th>Borrar</th>
                        <th>Show</th>
                    </tr>
                </thead>
                <tbody>
                    <% @libros.each do |libro| %>
                        <tr>
                            <td><%= libro.id %></td>
                            <td><%= libro.nombre %></td>
                            <td><%= libro.descripcion %></td>
                            <td><%= libro.paginas %></td>
                            <td><%= libro.precio %></td>
                            <td><%= link_to "Edit this libro", edit_libro_path(libro) %></td>
                            <td><%= button_to "Destroy this libro", libro, method: :delete %></td>
                            <td><%= link_to "Show this libro", libro %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </section>


</div>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Back to libros", libros_path %>
</div>

app/views/libros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @libro %>

<div>
  <%= link_to "Edit this libro", edit_libro_path(@libro) %> |
  <%= link_to "Back to libros", libros_path %>

  <%= button_to "Destroy this libro", @libro, method: :delete %>
</div>

app/views/phantom/generic.html.erb
<div id="main">
						<div class="inner">
							<h1>Generic Page</h1>
							<span class="image main"><img src="images/pic13.jpg" alt="" /></span>
							<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
							<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
						</div>
</div>

app/views/phantom/index.html.erb
<div id="main">
						<div class="inner">
							<header>
								<h1>This is Phantom, a free, fully responsive site<br />
								template designed by <a href="http://html5up.net">HTML5 UP</a>.</h1>
								<p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
							</header>
							<section class="tiles">
								<article class="style1">
									<span class="image">
                                        <%= image_tag("pic01.jpg", alt: "...") %> 
									</span>
									<a href="generic.html">
										<h2>Magna</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style2">
									<span class="image">
                                    <%= image_tag("pic02.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Lorem</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style3">
									<span class="image">
                                    <%= image_tag("pic03.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Feugiat</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style4">
									<span class="image">
                                    <%= image_tag("pic04.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Tempus</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style5">
									<span class="image">
                                    <%= image_tag("pic05.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Aliquam</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style6">
									<span class="image">
                                    <%= image_tag("pic06.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Veroeros</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style2">
									<span class="image">
                                    <%= image_tag("pic07.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Ipsum</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style3">
									<span class="image">
                                    <%= image_tag("pic08.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Dolor</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style1">
									<span class="image">
                                    <%= image_tag("pic09.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Nullam</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style5">
									<span class="image">
                                    <%= image_tag("pic10.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Ultricies</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style6">
									<span class="image">
                                    <%= image_tag("pic11.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Dictum</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style4">
									<span class="image">
                                    <%= image_tag("pic12.jpg", alt: "...") %>
									</span>
									<a href="generic.html">
										<h2>Pretium</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
							</section>
						</div>
					</div>

app/views/shared/__main.html.erb
<div id="main">
						<div class="inner">
							<header>
								<h1>This is Phantom, a free, fully responsive site<br />
								template designed by <a href="http://html5up.net">HTML5 UP</a>.</h1>
								<p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
							</header>
							<section class="tiles">
								<article class="style1">
									<span class="image">
										<img src="images/pic01.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Magna</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style2">
									<span class="image">
										<img src="images/pic02.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Lorem</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style3">
									<span class="image">
										<img src="images/pic03.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Feugiat</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style4">
									<span class="image">
										<img src="images/pic04.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Tempus</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style5">
									<span class="image">
										<img src="images/pic05.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Aliquam</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style6">
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Veroeros</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style2">
									<span class="image">
										<img src="images/pic07.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Ipsum</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style3">
									<span class="image">
										<img src="images/pic08.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Dolor</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style1">
									<span class="image">
										<img src="images/pic09.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Nullam</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style5">
									<span class="image">
										<img src="images/pic10.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Ultricies</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style6">
									<span class="image">
										<img src="images/pic11.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Dictum</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style4">
									<span class="image">
										<img src="images/pic12.jpg" alt="" />
									</span>
									<a href="generic.html">
										<h2>Pretium</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
							</section>
						</div>
					</div>

app/views/shared/_footer.html.erb
<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<input type="text" name="name" id="name" placeholder="Name" />
										</div>
										<div class="field half">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" placeholder="Message"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="primary" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="#" class="fab fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands style2 fab fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands style2 fab fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
									<li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
									<li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

app/views/shared/_header.html.erb

					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="index.html" class="logo">
									<span class="symbol"><%= image_tag("logo.svg", alt: "...") %></span><span class="title">Phantom</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

app/views/shared/_menu.html.erb
<nav id="menu">
<h2>Menu</h2>
<ul>
    <li><%= link_to 'Home', 'index' %></li>
    
    <li><%= link_to 'Generic', 'generic' %></li>
    
    <li><%= link_to 'Elements', 'elements' %>
    </li>
    <li><a href="generic.html">Consequat dolor</a></li>
    <li><a href="elements.html">Elements</a></li>
</ul>
</nav>

app/views/welcome/index.html.erb
<h1>Indice de la página</h1>
<p>Acabo de modificar el archivo
app/views/pages/index.html.erb</p>
<h2>Hola Mundo!!</h2>
(c)Copyright <%= Time.now.year %>
<% if Time.now.year >= 2018 %>
<p> Versión 2.0 </p>
<% else %>
<p> versión 1.0 </p>
<% end %>


<p> esta es la fecha y la hora: <%= Time.now %> </p>
<p> esta es el año: <%= Time.now.year %> </p>

app/views/zelda/mostrar.html.erb
<h1> La zelda es un gatito </h1>